
package mathrices;

import javax.swing.JOptionPane;

/**
 *
 * @author ariat
 */
public class T2_7EXAMEN extends javax.swing.JFrame {

    /**
     * Creates new form T2_1EXAMEN
     */
    public T2_7EXAMEN() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        s1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        v1 = new javax.swing.JButton();
        v2 = new javax.swing.JButton();
        v4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        v5 = new javax.swing.JRadioButton();
        v6 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        s1.setBackground(new java.awt.Color(0, 0, 153));
        s1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setText("Siguiente");
        s1.setEnabled(false);
        s1.setFocusable(false);
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 590, 90, 60));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Regresar");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v1.setBackground(new java.awt.Color(0, 0, 153));
        v1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        v1.setForeground(new java.awt.Color(255, 255, 255));
        v1.setText("Verificar");
        v1.setFocusable(false);
        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });
        jPanel1.add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 90, 60));

        v2.setBackground(new java.awt.Color(0, 0, 153));
        v2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        v2.setForeground(new java.awt.Color(255, 255, 255));
        v2.setText("Verificar");
        v2.setEnabled(false);
        v2.setFocusable(false);
        v2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2ActionPerformed(evt);
            }
        });
        jPanel1.add(v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 90, 60));

        buttonGroup2.add(v4);
        v4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        v4.setText("0 (cero)");
        v4.setFocusable(false);
        v4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v4ActionPerformed(evt);
            }
        });
        jPanel1.add(v4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("El determinante de una matriz y el de su transpuesta son...");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 44));

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rb1.setText("Distintos");
        rb1.setFocusable(false);
        jPanel1.add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rb2.setText("Iguales");
        rb2.setFocusable(false);
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        jPanel1.add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("|At|=");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, 44));

        buttonGroup2.add(v5);
        v5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        v5.setText("|At|");
        v5.setFocusable(false);
        v5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v5ActionPerformed(evt);
            }
        });
        jPanel1.add(v5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, -1, -1));

        buttonGroup2.add(v6);
        v6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        v6.setText("|A|");
        v6.setFocusable(false);
        v6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v6ActionPerformed(evt);
            }
        });
        jPanel1.add(v6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1410, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void v5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v5ActionPerformed

    private void v4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v4ActionPerformed

    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
        // Verifica si las respuestas son correctas
        if(rb1.isSelected()){
            JOptionPane.showMessageDialog(null, "INCORRECTO");
            rb1.setEnabled(false);
            rb2.setEnabled(false);
           
            v1.setEnabled(false);
            v2.setEnabled(true);
        }
        if(rb2.isSelected()){
            JOptionPane.showMessageDialog(null, "CORRECTO");
            rb1.setEnabled(false);
            rb2.setEnabled(false);
          
            v1.setEnabled(false);
            v2.setEnabled(true);
        }
     
        
       
        
        
    }//GEN-LAST:event_v1ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    T2_8EXAMEN c=new T2_8EXAMEN ();
        c.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_s1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   T2_6EXAMEN c=new T2_6EXAMEN ();
        c.setVisible(true);
        this.dispose();        // TODO add your handling code here:
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void v2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v2ActionPerformed
        // TODO add your handling code here:
        if(v4.isSelected()){
            JOptionPane.showMessageDialog(null, "INCORRECTO");
            v4.setEnabled(false);
            v5.setEnabled(false);
            v6.setEnabled(false);
            v2.setEnabled(false);
            s1.setEnabled(true);
        }
        if(v5.isSelected()){
            JOptionPane.showMessageDialog(null, "INCORRECTO");
            v4.setEnabled(false);
            v5.setEnabled(false);
            v6.setEnabled(false);
            v2.setEnabled(false);
            s1.setEnabled(true);
        }
        if(v6.isSelected()){
            JOptionPane.showMessageDialog(null, "CORRECTO");
            v4.setEnabled(false);
            v5.setEnabled(false);
            v6.setEnabled(false);
            v2.setEnabled(false);
            s1.setEnabled(true);
        }
        
    }//GEN-LAST:event_v2ActionPerformed

    private void v6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T2_7EXAMEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T2_7EXAMEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T2_7EXAMEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T2_7EXAMEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T2_7EXAMEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JButton s1;
    private javax.swing.JButton v1;
    private javax.swing.JButton v2;
    private javax.swing.JRadioButton v4;
    private javax.swing.JRadioButton v5;
    private javax.swing.JRadioButton v6;
    // End of variables declaration//GEN-END:variables
}
